export const categories = [
  "Full-Stack",
  "Back-End",
  "Front-End",
  "Mobile",
  "DevOps",
  "Data Science",
  "Machine Learning",
  "UI/UX",
  "Game Development",
  "Blockchain",
  "Cybersecurity",
  "Cloud Computing",
  "Internet of Things",
  "Augmented Reality",
  "Virtual Reality",
  "Artificial Intelligence",
  "Robotics",
  "Software Development",
  "Web Development",
  "Open Source",
  "Content Creation",
  "Community Building",
  "Education",
  "Research",
  "Entrepreneurship",
  "Other",
] as const;

export type Category = (typeof categories)[number];
